### ISSUE TITLE
QoL command m

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#18]
If inside math editor window, command m will take you out of math editor window (not minimize), acting similarly to escape. # #

**Comment by 18nshinagawa** [comment]
will fix this as part of #19

**Comment by 18nshinagawa** [comment]
the thing is, escape works across all of code, math, link, etc. having to differentiate might be weird for the user?

I think the idea here is to prevenDefault() on those object keys to prevent minimizing, but still use escape as the only key to get out.
