### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#24]
TypeError: o.commonAncestorContainer.parentElement.closest(...) is nullNotes.js:300:56
    value Notes.js:300
    value Notes.js:176

**Comment by 18nshinagawa** [comment]
Backspace? then drag and drop, click, click?
But clicking inside math

but seperating the click vs keyboard is going to fix this issue according to #19

**Comment by 18nshinagawa** [comment]
this should be fixed but it creates issue #26
