### ISSUE TITLE
Justifiable

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#36]
Add left justified, right justified (not sure of the term for these), center justified

**Comment by lzhaxi** [comment]
I mean with commands

**Comment by 18nshinagawa** [comment]
I don't like left, right, etc. There should be a styling option like the font option to do it but not for individual paragraphs (bad document practice) just like **underline**.

**Comment by lzhaxi** [comment]
Potentially add center alignment for use with titles

**Comment by 18nshinagawa** [comment]
now, that's a good use for centering! But I'm buy fixing page breaks

**Comment by 18nshinagawa** [comment]
text centered for headings, default font Georgia

let's see how this goes. will close but post a suggestion for more fredom

**Comment by lzhaxi** [comment]
Text is not centered for headings

**Comment by 18nshinagawa** [comment]
what????? it should be though.

**Comment by 18nshinagawa** [comment]
I swear it was at home

**Comment by 18nshinagawa** [comment]
I think I forgot to push it because I was working on experimental multi file system that i didn't want to push yet

**Comment by 18nshinagawa** [comment]
yep it's not centered lol will fix
