### ISSUE TITLE
Change cursor color

### ISSUE THREAD

**Issue by 18nshinagawa** [18nshinagawa/notes#39]
blue is nice

**Comment by lzhaxi** [comment]
Is blue actually nice

**Comment by 18nshinagawa** [comment]
yes

maybe give it try for a week and if you're still bothered

**Comment by lzhaxi** [comment]
Not consistent with math, code, etc.

**Comment by 18nshinagawa** [comment]
will consider

**Comment by 18nshinagawa** [comment]
will make this part of ui css update
