### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#44]
With heading 1, if I type spaces or other characters they should be in the title

**Comment by lzhaxi** [comment]
Math in title is broken, appears twice

**Comment by 18nshinagawa** [comment]
it's because the id of title doens't have spaces in it;

note to self:
**make title based on innertext, not the id of the first h1**

also, i think this is the older version where only the first space gets deleted.

**Comment by 18nshinagawa** [comment]
lol this is actually a good issue thanks! (no sarcasm)

**Comment by 18nshinagawa** [comment]
**i think fix here is to just get rid of mathML. it's not used and this app has poor browser compability anyway it dosn't need a fallback**

to get rid, just get the string, regex Mathml out of it

**Comment by 18nshinagawa** [comment]
also don't bold titles by default (no need)

**Comment by 18nshinagawa** [comment]
fixed; will be pushed with next update

**Comment by 18nshinagawa** [comment]
overturned this decision based on the fact that mathml is important for screen readers

Also, math shouldn't be in title

**Comment by lzhaxi** [comment]
> overturned this decision based on the fact that mathml is important for screen readers
> 
> Also, math shouldn't be in title


Overturned which part of the decision?
I think spaces are important.
@18nshinagawa

**Comment by 18nshinagawa** [comment]
just the math part, sorry!! spaces are working as expected

math will show twice if it's in the title, so just don't put it in title
