### ISSUE TITLE
Cursor is cut off

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#47]
When initializing a new math statement, cursor is cut off

**Comment by lzhaxi** [comment]
Also for code

**Comment by 18nshinagawa** [comment]
more details please thanks

**Comment by lzhaxi** [comment]
<img width="94" alt="Screen Shot 2019-07-08 at 11 29 00" src="https://user-images.githubusercontent.com/47646514/60822528-9aaf4700-a173-11e9-90a4-5ee9072e70fe.png"> vs 
<img width="92" alt="Screen Shot 2019-07-08 at 11 29 55" src="https://user-images.githubusercontent.com/47646514/60822585-b9154280-a173-11e9-8840-ebb7be5410db.png">

The difference between those two is that I typed one character and deleted it in the second screenshot

**Comment by 18nshinagawa** [comment]
first one is actually empty

second one has <br>, I think. Will make it so there is <br> by default.

But also, the br is an issue for links and things: **fix this**

doesn't seem to be an issue for windows though

**Comment by 18nshinagawa** [comment]
fixed first issue; onto other issue

**Comment by 18nshinagawa** [comment]
should be fixed by making the boxes pre, not div
