### ISSUE TITLE
math in bullets

### ISSUE THREAD

**Issue by 18nshinagawa** [18nshinagawa/notes#5]
probably also with code, etc.

But enter on bullets continues math? is a mess

**Comment by lzhaxi** [comment]
Deleting bullets takes a variable amount of deletes, sometimes 1, sometimes 3

**Comment by 18nshinagawa** [comment]
with or without math?

**Comment by lzhaxi** [comment]
I assumed it was because of math but I'll check
EDIT: Yes it's because of math, no math bullets work normally (one delete)

**Comment by 18nshinagawa** [comment]
lol I really should fix this issue; busy with the keyboard thing last week and also, working on new things is always more fun than fixing bugs . . . but maybe this week

**Comment by 18nshinagawa** [comment]
temporarily solved but will watch out for this issue when the new selection is implemented

lol this issue is so old it got accidentally solved
