### ISSUE TITLE
Large math window

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#55]
If math window becomes too large, window cannot scroll back up
<img width="1256" alt="Screen Shot 2019-07-09 at 11 50 35" src="https://user-images.githubusercontent.com/47646514/60903680-c861c200-a23f-11e9-881c-5b8f49edcfdc.png">

**Comment by 18nshinagawa** [comment]
lol! I thought that was an actual equation that you needed for class and was like
... ew that's messy but then i realize that you're just bug testing :) thanks!

**Comment by 18nshinagawa** [comment]
yay working
