### ISSUE TITLE
Find function

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#56]
Add find for the math window.
Also add find and replace everywhere.

**Comment by lzhaxi** [comment]
Command f when the find window is open should close the find window if there is nothing in the find window, however currently it just brings back what I had previously tried to find, forcing me to click the x button in order to get out of find

**Comment by 18nshinagawa** [comment]
escape key should work for getting out of find window normally

, and i don't know how one would get out of without pressing the escape key or pressing the x button unless i make my own system

for now, don't preventdefault() on escape key.

**Comment by 18nshinagawa** [comment]
considerations for find and replace:
1. unlike some browser's functionalities, you can't highlight all matches, but highlighting the current match is possible
2. maybe an idea would be to combine the existing find system with a custom replace sytsem?
3. replace all is not that difficult. just select entire document, insertHTML of regex replace
  * however, be careful where to replace and where not to. For example, replacing divs should not affect div tags. But, for math and code objects, etc, the replace should replace both content and the dataset attribute.

**Comment by 18nshinagawa** [comment]
find and replace all is pretty easy:

two boxes: one for find, the other for replace
press enter on either to find the string, replace all; as mentioned above, also works within objects and perhaps also for the editing menu

**Comment by 18nshinagawa** [comment]
that was an accident

anyway, finding and replacing (not all) is harder because i have to either implement a node walker (traverse through dom until i get to the text node, look for text there) or use the built in search

replacing is easier - just insertText

**Comment by 18nshinagawa** [comment]
use regex for find and replace all? would be first step

**Comment by 18nshinagawa** [comment]
considering the severity of the bugs and importance of other enhancements, this will be either forgotten or considered later

need basic features before working on new things; otherwise, can't catch up
