### ISSUE TITLE
Multiple files refresh

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#57]
Command shift R for multiple files gives 404 error

**Comment by 18nshinagawa** [comment]
can you clarify where that happens?

Like the menu that lists the files?

**Comment by 18nshinagawa** [comment]
I guess it happens when you have, for example, ~/notes/file1 open

and the command shift R

**Comment by 18nshinagawa** [comment]
simple solution: disable command shift r

**Comment by lzhaxi** [comment]
If you disable command shift r then you can't update the thing when you are in ~/notes/file1 ?

**Comment by 18nshinagawa** [comment]
true true

maybe i'll try to find a better solution but . . .

**Comment by 18nshinagawa** [comment]
not being able to command shift r in a branched address is probably better than seeing the message

**Comment by lzhaxi** [comment]
Right but being able to command shift r and making it work is best

**Comment by 18nshinagawa** [comment]
lol does it matter though

can i just mark this nofix and close

like i know it's a bit inconvenient but it takes like an extra half second and at least you don't have to spam command shift r like i do whenever i update every 30 seconds lol

and eventually, you shouldn't have to comman shift r much

but also, I think this is a github hosting thing, technically, and i have no control over it, I think

**Comment by 18nshinagawa** [comment]
I really don't think it can be fixed as long as it's hosted on github; will reconsider if we move
