### ISSUE TITLE
display button works but is ugly

### ISSUE THREAD

**Issue by 18nshinagawa** [18nshinagawa/notes#60]
like, there are ugly things . . .

and then there's the display button.

Ew! Fix it pleas.

**Comment by lzhaxi** [comment]
I don't think it's doing display math? doesn't look any different when I press display except it goes to the center

**Comment by 18nshinagawa** [comment]
I think it's working now but it still needs a ui upgrade to make it clearer when it's focused

**Comment by 18nshinagawa** [comment]
okay this is going under general ui fix because good enough for now
