### ISSUE TITLE
Certain keys don't work in math

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#61]
S, O, and P do not work
S highlights the math

**Comment by lzhaxi** [comment]
Pasting works, thankfully

**Comment by 18nshinagawa** [comment]
s, o, and p (with command) are supposed to work outside the editor

however, right now, it preventDefualt() any of those keys even without command

**fix by *not* preventing default on the keys, but rather passing command + s, o, p right to the handleInputIframe() method
