### ISSUE TITLE
compatibility issues with font

### ISSUE THREAD

**Issue by 18nshinagawa** [18nshinagawa/notes#66]
**issue**: monaco font doesn't exist on windows
**solution**: use roboto for normal text, roboto mono for code, roboto slab
**advantages**: roboto can be loaded from google fonts library directly using css, so it should work on all computers

**Comment by lzhaxi** [comment]
Why roboto?

**Comment by 18nshinagawa** [comment]
1. roboto and its relatives (roboto slab, roboto mono) are hosted for free on google fonts; it's also well-maintained because it's basically? made by google and is used in all of their things

advantage of google fonts is that anyone can use it

and of course, there are other fonts that are usable from google fonts but i thought robot family would be a good starting point because it has serif, sans serif, and monspace

but i'd be happy to look for other pairings that work

**Comment by 18nshinagawa** [comment]
set default fonts to roboto family
