### ISSUE TITLE
Command still lights up the top bar as if I did the actual command

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#67]
For example, when I type command + m to get into math, the Window part on the toolbar lights up as if I did command + m for minimize. Not sure if there's a way to get rid of that (that's why I didn't bring it up the first time I noticed) but figured it should be documented anyway.

Could be confusing for newer users.

**Comment by 18nshinagawa** [comment]
it doesn't actually minimize though, right? Same happens for other commands, I think, and I really doubt I can fix it. But just to make sure, you mean the things at the top that say like "File", "Edit", "View", etc., right?

**Comment by lzhaxi** [comment]
Yes, it's fine if you can't fix it, just looks bad.
