### ISSUE TITLE
QoL cursor

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#7]
When beginning the document, it may be hard to click on the document.
Also, when I try to click in a math equation (or something similar), I would like the cursor to be where I clicked in the math equation, not default set to the beginning of i.t

**Comment by 18nshinagawa** [comment]
I think the cursor is fine? But can you screenshot if it shows up like that?

**Comment by lzhaxi** [comment]
The cursor does not start blinking until I type some letter
