### ISSUE TITLE
Saved indicator

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#75]
Would be nice to have an indicator on when you make changes and haven't saved them yet

**Comment by 18nshinagawa** [comment]
i have a few ideas for this but don't know which is best:

1. bar on side/top/bottom that goes from red to blue/green? (original idea that i like haha)
2. indicator on title/title icon that goes away once saved (idea from windows, visual studio code)

with the bar, it could also show last saved? will look for ideas online and try implementing one or a few

**Comment by 18nshinagawa** [comment]
but if you have an idea, post here

**Comment by 18nshinagawa** [comment]
I think the best idea is something that is moving until you save and then it stops

**Comment by lzhaxi** [comment]
Idea: red bar on the side, potentially corresponding with where the new changes are made. Goes away (or turns blue?) when the user saves.

**Comment by 18nshinagawa** [comment]
i like the idea; some others used by various software:

* classic * (asterisk) before/after filename
  * for example, if you have `file` and it's not saved, it appears as `*file` or `file*` or something
but this is pretty subtle;

**Comment by lzhaxi** [comment]
> i like the idea; some others used by various software:
> 
> * classic * (asterisk) before/after filename
>   
>   * for example, if you have `file` and it's not saved, it appears as `*file` or `file*` or something
>     but this is pretty subtle;

Might be better if you implement the first idea...

> Idea: red bar on the side, potentially corresponding with where the new changes are made. Goes away (or turns blue?) when the user saves.

...if you don't implement the corresponding with where the new changes are made thing for this idea.

**Comment by 18nshinagawa** [comment]
very hard to detect if file was undone to an equivalent state (probably would have to check entire file against itself; bad big O)

**Comment by lzhaxi** [comment]
Unnecessary to detect if file was undone (unless undo was used), other apps don't either

**Comment by 18nshinagawa** [comment]
some good apps do, but i agree that it's unnecessary

**Comment by 18nshinagawa** [comment]
how about to start, put a simple green bar if saved, red bar if not saved along left edge of paper?

**Comment by 18nshinagawa** [comment]
![Screenshot_2019-07-18 ab](https://user-images.githubusercontent.com/51770153/61472549-ac9ea000-a952-11e9-8270-a860fd1153e1.png)

**Comment by 18nshinagawa** [comment]
![image](https://user-images.githubusercontent.com/51770153/61472644-dfe12f00-a952-11e9-8eb4-6af9f0d7104c.png)

**Comment by 18nshinagawa** [comment]
i kind of like how minimal it is? subtle but noticable

maybe this + message upon exit will do

**Comment by lzhaxi** [comment]
Are you also planning to prevent the user from closing out the window when they have unsaved changes? Like a pop-up window

**Comment by 18nshinagawa** [comment]
It's firefox, so It's harder to implement things in general due to security concerns

but I think i should be able to do a simple message like

"are you sure you want to leave? you haven't saved file" or something with a "leave anyway" or "stay" button

**Comment by 18nshinagawa** [comment]
oops accidentally closed

**Comment by 18nshinagawa** [comment]
above suggestions including message (no custom message, but default is fine) implemented
