### ISSUE TITLE
Clicking on math that is far apart from each other

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#77]
In a relatively large document, I have multiple equations at the top and at the bottom. After clicking on an equation at the top, I clicked on the equation at the bottom, and the page scrolls weirdly and doesn't show me the equation at the bottom until I scroll down.

**Comment by 18nshinagawa** [comment]
scrollIntoView might be a good idea here

will definitely check this out

**Comment by 18nshinagawa** [comment]
either prevent default scroll or scroll down to element


also, every time you type something in, for example, math, it scrolls down because the math is long; fix this too

**Comment by 18nshinagawa** [comment]
simple fix by deleting manual focus on first text box thing
