### ISSUE TITLE
Math equation issue, selecting when deleting

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#81]
If I have something like 
(math equation) (normal text) (math equation)
I'm in the second math equation, I delete all of it, I exit math. Then, when I press delete, the normal text is not deleted, the selector skips over the normal text and tries to delete the first math equation.

**Comment by 18nshinagawa** [comment]
putting this also under #62

**Comment by 18nshinagawa** [comment]
found out issue:

confused  `children` with `childNodes` `children` only includes elements, while `childnodes` also includes text nodes

**Comment by lzhaxi** [comment]
Another similar issue: when I delete all of it, then type one more character (without exiting math this time), the previous characters come back.

**Comment by 18nshinagawa** [comment]
happens when you press `command + m` almost immediately after typing another character

happens because undo command is executed;

instead of using a blank `.selection.element` as a placeholder, insert for first time

**Comment by 18nshinagawa** [comment]
fixed
