### ISSUE TITLE
Newline, bold goes away

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#82]
If I'm in **bold** then I think going to a newline in the vast majority of circumstances, you wouldn't need to still be in bold, so it should go away after pressing enter.

**Comment by 18nshinagawa** [comment]
but then, how often do you end a sentence with bold?

**Comment by lzhaxi** [comment]
Generally I don't end a sentence with bold, I have like a mini header like **Example:** then I want a newline after that with the example

**Comment by 18nshinagawa** [comment]
maybe i'll add h4 for that?

i think bold should only be used in paragraph

the question is, do you need h5 and h6?

**Comment by lzhaxi** [comment]
Yeah it's in paragraph, i don't need header for this, I'm just saying if you ever do end sentence with bold, the next newline shouldn't be bold automatically.

**Comment by 18nshinagawa** [comment]
hmm

**Comment by 18nshinagawa** [comment]
but you called it a mini header and also, that's the only thing on the line?

which makes it a header, right?

**Comment by 18nshinagawa** [comment]
wait; i forgot that  headers wouldn't be bolded so that's useless; anyway, is pressing command b again too much work :(

**Comment by lzhaxi** [comment]
It's minor, not extremely important, but I think it makes more sense to have bold off initially.

**Comment by lzhaxi** [comment]
Math should also take away the bold

**Comment by 18nshinagawa** [comment]
There's no unbold command though; it's just the bold command

so like the whole option to press command 2 again when in heading 2 to turn it back into paragraph, this requires some detection; put this under selection thing
