### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#83]
I'm not sure how to reproduce the error, but somehow when I was making a header (command + 2), enter did not take me out of header and I had to delete everything up to before the header and make another header in order for me to get back into normal text. Just documenting in case you come across this issue again.

I suggest having command + 2 take you out of header (currently, you can only get out of header by pressing enter).

**Comment by 18nshinagawa** [comment]
command 0 formats everything back to paragraph so if that ever happens again, after the newline, press command 0

I think that should work but let me know if it happens again

**Comment by lzhaxi** [comment]
like #63, I would say it should be similar, where doing it again gets you out of it. Good to know though, I didn't know that.

**Comment by 18nshinagawa** [comment]
that would require detecting the parent's tagname, which is a bit complicated

with the reorganizing, I think i'll create a new method that returns the parentelement of a selection, which would make this task easy, but for now, closing this
