### ISSUE TITLE
Downloading file

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#90]
Sometimes (not sure how to duplicate issue) saving file gives me a corrupted (unable to read) html file and a directory called filename_files with a bunch of css and javascript things, and the readable file is within that directory

**Comment by 18nshinagawa** [comment]
can you find out where this happens? For example, does it work correctly within

1. the inside of the editor (cursor in document)
2. while in a math editor box
3. other?

and also, i just want to make sure that the dialogue box looks different, right?

**Comment by lzhaxi** [comment]
Not sure what you mean. I actually already deleted the corrupted file so I can't show you, but basically if I tried to open it there was a bunch of nonsense. It's not a bug within the program, just a bug with downloading. If I went back to the directory where the file is stored in cache, it looks fine. I didn't try dragging and dropping the file back into the program.

**Comment by 18nshinagawa** [comment]
lol sorry i meant when you downloaded the file

**Comment by 18nshinagawa** [comment]
@lzhangix said it's probably from the time when #78
