### ISSUE TITLE
Math equation selection cursor

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#93]
If I have a math equation and I open and close it, then make a new math equation in a different line, when I go out of that math equation the cursor goes back to the first math equation.

**Comment by lzhaxi** [comment]
Also, after exiting the math, if I had a space before the math, the cursor ignores the space and goes back to before the space.

**Comment by 18nshinagawa** [comment]
under selection issue

**Comment by 18nshinagawa** [comment]
kind of fixed
