### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#96]
Quotes are always facing backwards

**Comment by 18nshinagawa** [comment]
i think this is just the font but i'll investigate

**Comment by 18nshinagawa** [comment]
yep it's the font . . .

options:
1. make all the quotes straight
2. make all the quotes backwards
3. keep it the way it is
4. automatically detect quote pairs to correct orientation
5. control + " to insert quote pair/wrap selection in quotes?

i am thinking that a combination of 5 and 1 would be best
4 is nice but 1. it would take too much processing power wasted to detect every single quotation mark

**Comment by 18nshinagawa** [comment]
@lzhangix let me know what you think

**Comment by 18nshinagawa** [comment]
actually, i think 3 + 5 is best

**Comment by 18nshinagawa** [comment]
another idea!!!

if you use left shift, open quotes
if you use right shift, close quotes

**Comment by 18nshinagawa** [comment]
^ would be a very simple solution and quite practical.

**Comment by 18nshinagawa** [comment]
except that I realized that single quotes won't work this way. But I think I'll just pretend they're all apostrophes?

**Comment by 18nshinagawa** [comment]
implemented idea
